TT2_Exam/Controllers/CultureController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

public class CultureController : Controller
{
    [HttpGet]
    public IActionResult SetCulture(string culture, string returnUrl)
    {
        if (!string.IsNullOrWhiteSpace(culture))
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions
                {
                    Expires = DateTimeOffset.UtcNow.AddYears(1),
                    IsEssential = true
                }
            );
        }

        return LocalRedirect(returnUrl ?? "/");
    }
}

TT2_Exam/Controllers/LibraryController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using TT2_Exam.Data;
using TT2_Exam.Models;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace TT2_Exam.Controllers;

[Authorize]
public class LibraryController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserManager<UserModel> _userManager;

    public LibraryController(AppDbContext context, UserManager<UserModel> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        var userId = _userManager.GetUserId(User);

        var libraryItems = await _context.UserLibrary
            .Include(c => c.VideoGame)
            .Where(c => c.UserId == userId)
            .ToListAsync();

        return View(libraryItems);
    }
    
}

TT2_Exam/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.Extensions.Localization
@using TT2_Exam.Utility
@inject SignInManager<UserModel> SignInManager
@inject UserManager<UserModel> UserManager
@inject IStringLocalizerFactory LocalizerFactory
@{
    var SharedLocalizer = LocalizerFactory.Create("SharedResources", "TT2_Exam");
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-1 mt-1">
        <div class="container justify-content-center">
            <div class="d-flex w-100" style="max-width: 60%;">
                    
                <!-- Left: Logo -->
                <div class="d-flex align-items-center me-auto">
                    <a class="navbar-brand" href="#">
                        <img src="~/img/hades-symbol.svg" alt="Logo" class="logo">
                    </a>
                </div>
                    
                <!-- Center: Nav links -->
                <div class="d-flex justify-content-center align-items-center flex-grow-1">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                        <ul class="navbar-nav fw-bold fs-5">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer["Home"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Store" asp-action="Index">@SharedLocalizer["Store"]</a>
                            </li>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Library" asp-action="Index">@SharedLocalizer["Library"]</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin") || User.IsInRole("Publisher"))
                            {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="VideoGame" asp-action="Index">@SharedLocalizer["Publishing"]</a>
                            </li>
                            }
                            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">@SharedLocalizer["Admin"]</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                    
                <!-- Right: User info -->
                <div class="d-flex align-items-center ms-auto">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                        <ul class="navbar-nav fs-7">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item"><a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index">@User.Identity?.Name</a></li>
                            <li class="nav-item">
                                <form asp-area="Identity" asp-page="/Account/Logout" method="post" id="logoutForm" class="form-inline">
                                    <li class="nav-item"><a class="nav-link" asp-area="Identity" asp-page="/Account/Logout" onchange="this.form.submit()">@SharedLocalizer["Logout"]</a>
                                </form>
                            </li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Cart" asp-action="Index">@SharedLocalizer["Cart"]</a></li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link" asp-area="Identity" asp-page="/Account/Login">@SharedLocalizer["Login"]</a></li>
                            <li class="nav-item"><a class="nav-link" asp-area="Identity" asp-page="/Account/Register">@SharedLocalizer["Register"]</a></li>
                        }
                        </ul>
                    </div>
                </div>
                    
            </div>
        </div>
    </nav>
</header>

TT2_Exam/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Localization
@using TT2_Exam.Utility
@using Microsoft.AspNetCore.Http.Extensions
@inject IStringLocalizerFactory LocalizerFactory
@{
    var SharedLocalizer = LocalizerFactory.Create("SharedResources", "TT2_Exam");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TT2_Exam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/aspform.css" asp-append-version="true"/>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

<div class="d-flex flex-column min-vh-100">
    
    <!-- Header -->
    @await Html.PartialAsync("_Header")
    
    
    <!-- Body -->
    <div class="flex-grow-1 container">
        <main class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    
    <!-- Footer -->
    <footer class="footer text-muted mt-auto py-3">
        <div class="container">
            &copy; 2025 - TT2_Exam -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> -
            <a href="@Url.Action("SetCulture", "Culture", new { area = "", culture = "lv-LV", returnUrl = Context.Request.Path + Context.Request.QueryString })">LV</a>
            <a href="@Url.Action("SetCulture", "Culture", new { area = "", culture = "en-US", returnUrl = Context.Request.Path + Context.Request.QueryString })">EN</a>
        </div>
    </footer>

</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>